### ISSUE TITLE
Needed support for aarch64-unknown-linux-musl and README update

### ISSUE THREAD

**Issue by StachowiakDawid** [tectonic-typesetting/tectonic-ci-support#23]
Hello,
I'm a maintainer of an Overleaf fork which adds Tectonic to available compilers (https://github.com/overleaf/overleaf/compare/main...StachowiakDawid:overleaf:main). My main platform is M1 Pro & macOS, so I used `arm-unknown-linux-musleabihf` binary in the Docker image, but recently I've changed my Docker engine from Docker Desktop to Colima and was surprised by an error when trying to run Tectonic inside Colima, because Colima Alpine kernel doesn't support running 32-bit ARM binaries like Docker Engine Ubuntu kernel does.

I tried building `aarch64-unknown-linux-musl` binary myself, but I couldn't even build official `x86_64-unknown-linux-musl` using following commands:
```
./build.x86_64-unknown-linux-musl.sh
docker run --privileged --rm -v $(pwd):/alpine/home/rust/src tectonictypesetting/crossbuild:x86_64-unknown-linux-musl
```
because it couldn't find folders `/target` and `/cargo` at line 11 in `entrypoint.sh`
```
    for dir in proc sys dev project target cargo xargo rust tmp ; do
```
So I have two requests:
1. Could you add `aarch64-unknown-linux-musl` build to CI and include it in future releases?
2. Could you provide me information if this repository contains up-to-date scripts, so I know whether scripts are broken or my environment is broken?

**Comment by pkgw** [comment]
@StachowiakDawid My apologies for taking forever to reply to your nicely-prepared issue. The scripts in the repo are the latest ones that I've used, but I'm seeing the same sort of problem as you, so it looks like they need fixing to track a change ... somewhere. I'll see if I can address both of your requests.

**Comment by pkgw** [comment]
I don't have aarch64 working just yet, but the changes in this PR should hopefully explain this whole framework a lot better: https://github.com/tectonic-typesetting/tectonic-ci-support/pull/24

**Comment by pkgw** [comment]
OK, I think that I have solved the build problem (including a build hack that is, frankly, astonishing, but perfectly safe). I'll need to work through the rest of the CI but hopefully that's the last challenging blocker.

**Comment by pkgw** [comment]
Here's the Tectonic PR to add the aarch64-musl build there: https://github.com/tectonic-typesetting/tectonic/pull/1089

**Comment by pkgw** [comment]
That PR is merged, and the next release of Tectonic should include an official aarch64/musl binary. Between that and some hopefully useful README revisions, I'm going to go ahead and close this issue. Thanks again for filing a clear issue, and sorry for taking so long to follow up on it!
